// Sample class data - this will be replaced with actual class data
const SampleCourses = [
    {
        id: 1,
        name: "Computer Science 101",
        startTime: "09:00",
        endTime: "10:30",
        day: ['Monday', 'Wednesday'],
        weeks: 12,
        location: "Room 201",
        instructor: "Dr. Smith",
        courseDescription: "Introduction to Computer Science",
        color: "#4CAF50",
        isSelected: false
    },
    {
        id: 2,
        name: "Mathematics 205",
        startTime: "11:00",
        endTime: "12:15",
        day: ['Monday', 'Wednesday'],
        weeks: 12,
        location: "Room 305",
        instructor: "Prof. Johnson",
        courseDescription: "Advanced Calculus",
        color: "#2196F3",
        isSelected: false
    },
    {
        id: 3,
        name: "Physics Lab",
        startTime: "13:00",
        endTime: "14:00",
        day: ['Monday', 'Wednesday'],
        weeks: 12,
        location: "Lab 102",
        instructor: "Dr. Williams",
        courseDescription: "Experimental Physics",
        color: "#FF9800",
        isSelected: false
    },
    {
        id: 4,
        name: "English Literature",
        startTime: "16:45",
        endTime: "18:00",
        day: ['Monday', 'Wednesday'],
        weeks: 12,
        location: "Room 110",
        instructor: "Ms. Brown",
        courseDescription: "Study of classic English literature.",
        color: "#9C27B0",
        isSelected: false
    },
    {
        id: 5,
        name: "Chemistry 101",
        startTime: "19:00",
        endTime: "20:30",
        day: ['Monday'],
        weeks: 15,
        location: "Lab 210",
        instructor: "Dr. Green",
        courseDescription: "Introduction to Chemistry.",
        color: "#00BCD4",
        isSelected: false
    },
    {
        id: 6,
        name: "World History",
        startTime: "10:00",
        endTime: "12:15",
        day: ['Tuesday'],
        weeks: 14,
        location: "Room 120",
        instructor: "Mr. Lee",
        courseDescription: "Overview of world history.",
        color: "#FFC107",
        isSelected: false
    },
    {
        id: 7,
        name: "Art Appreciation",
        startTime: "13:00",
        endTime: "14:30",
        day: ['Tuesday'],
        weeks: 12,
        location: "Art Studio",
        instructor: "Ms. White",
        courseDescription: "Exploring visual arts.",
        color: "#E91E63",
        isSelected: false
    },
    {
        id: 8,
        name: "Economics",
        startTime: "11:30",
        endTime: "12:30",
        day: ['Thursday'],
        weeks: 12,
        location: "Room 220",
        instructor: "Dr. Black",
        courseDescription: "Principles of Economics.",
        color: "#3F51B5",
        isSelected: false
    },
    {
        id: 9,
        name: "Philosophy",
        startTime: "16:30",
        endTime: "17:45",
        day: ['Thursday'],
        weeks: 12,
        location: "Room 130",
        instructor: "Prof. Adams",
        courseDescription: "Introduction to Philosophy.",
        color: "#8BC34A",
        isSelected: false
    },
    {
        id: 10,
        name: "Statistics",
        startTime: "16:30",
        endTime: "15:45",
        day: ['Friday'],
        weeks: 12,
        location: "Room 140",
        instructor: "Dr. Clark",
        courseDescription: "Basics of Statistics.",
        color: "#FF5722",
        isSelected: false
    }
];

export default SampleCourses;